### ISSUE TITLE
Handle php errors on index generation

### ISSUE THREAD

**Issue by luishdez** [xolox/vim-easytags#104]
I've trying to use this plugin but sadly is unusable in most of the projects because the php errors thrown while index generation.

The index generator should handle the exceptions and not generate index for that classes, methods ect. that throw an error.

There is a lot of cases where you can not use all the files in a project, Eg: missing "optional" dependencies.

**Comment by xolox** [comment]
I'm going to close this issue now due to lack of feedback. If you can provide more information feel free to reopen this issue.
