### ISSUE TITLE
How do I exclude directories/files?

### ISSUE THREAD

**Issue by tom-james-watson** [xolox/vim-easytags#110]
I don't seem to be able to provide a list of files/directories to ignore? This is problematic when you have things like multiple node_modules that are many times the size of your actual codebase.

**Comment by tom-james-watson** [comment]
I also see there's an open pull request to add this functionality:

https://github.com/xolox/vim-easytags/pull/72

**Comment by jrean** [comment]
@tom-james-watson pretty easy. Inside your project directory (root) create a `.ctags` file (or you can use/create the default in `~/.ctags`).

Then inside add the following:
```
--exclude=directory/*
--exclude=directory/file.ext
...
```

Give a try to http://ctags.sourceforge.net/ctags.html and search for the `--exclude` option.
