### ISSUE TITLE
easytags not parsing ctags version correctly

### ISSUE THREAD

**Issue by decentral1se** [xolox/vim-easytags#132]
I am working with an install of ctags from [ctags.io](https://ctags.io/) and the version output is:

```
lwm$ ctags --version
Universal Ctags 0.0.0(72912f0), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec 17 2015, 18:33:44
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +debug, +option-directory, +coproc
```

I get the following error when I start up Vim afte installing easytags:

```
plugin/easytags.vim
easytags.vim 3.11: Plug-in not loaded because Exuberant Ctags 5.5 or newer is required while you have version 0.0.0 installed!
Press ENTER or type command to continue
```

If I do the following:

```
...
if !xolox#easytags#initialize('0.0.0')
...
```

Things run smoothly. So, I suppose this is a parsing error. I'll try and submit a PR for this when I am not woefully hungover, otherwise, if someone fixes it, it would be great :+1:

**Comment by still-dreaming-1** [comment]
Experiencing the exact same problem since I am using universal ctags as well. There is a pull request fix for this that someone made: https://github.com/xolox/vim-easytags/pull/133

**Comment by decentral1se** [comment]
@xolox bump!

**Comment by ghost** [comment]
@xolox bump!

**Comment by decentral1se** [comment]
Ha, still rotting here! Closing this one off boys and girls.
