### ISSUE TITLE
Please add ctags custom arguments only for easytags

### ISSUE THREAD

**Issue by oafish** [xolox/vim-easytags#70]
Because there are many vim plugins using ctags. Such as taglist and omnicomplete. If I change ~/.ctags it will impact all other plugins. 
For example if I want easytags generate tags file and it is used by omnicomplete too. I have to add --c++-kinds=+p --fields=+iaS --extra=+q in ~/.ctags. But taglist will display duplicate item in function name by using same ~/ctags config file.
Could you please add a option for ctags arguments only for easytags?

**Comment by xolox** [comment]
This is possible using the [g:easytags_opts](http://peterodding.com/code/vim/easytags#easytags_opts_option) option which was added in 075ffe9054dd71f8c2f26fe9cfa4fd5200e6af96 (version 3.9) in November 2014. Sorry for not following up here earlier. Happy Vimming!
