### ISSUE TITLE
easytags isn't creating tags for c++ class

### ISSUE THREAD

**Issue by ramon-oliveira** [xolox/vim-easytags#91]
Here is my .vimtags file:
![tags](https://cloud.githubusercontent.com/assets/4665205/3941471/bf94d2b0-252c-11e4-85bb-7627e15d98c2.png)

And it's possible to see that it's not highlighting my class in my file test.cpp :

![code](https://cloud.githubusercontent.com/assets/4665205/3941482/23ab36d6-252d-11e4-9f10-528bb6ec2faf.png)

Anyone knows how to solve this?

**Comment by davidkennedydev** [comment]
Ok, at principle i believe that's my problem, but searching vim with `:tag NamespaceX::ClassNameX::methodName` this points correctly, but if i just puts the cursos above a `methodName` call and use `<c-]>`  this points incorrectly.
This a problem on vim-easytags plugins or a problem with the own `<c-]>` map to go to tag on VIM?
